### PR TITLE
Fix RSpec/InstanceVariable inside custom matcher

### LINKED ISSUE #852: RSpec/InstanceVariable should ignore variables inside matchers.
RSpec/InstanceVariable is flagging instance variables inside matchers embedded in spec files. AFAIK instance variables are necessary for anything but a trivial matcher and replacing them with the suggested local variable, let, or method call would be inappropriate.

An example from the RSpec docs: [chained method with argument](https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/custom-matchers/define-matcher-with-fluent-interface#chained-method-with-argument)

```
RSpec::Matchers.define :be_bigger_than do |first|
  match do |actual|
    (actual > first) && (actual < @second)
  end

  chain :and_smaller_than do |second|
    @second = second
  end
end
```

An example of writing a matcher which is a wrapper around another matcher and passing through the failure message.

```
  matcher :look_like_a_thing do
    match do |thing|
      @matcher = have_attributes(...)

      @matcher.matches?(thing)
    end

    failure_message do
      @matcher.failure_message
    end
  end
```

I propose `IgnoreMatchers` defaulting to `true`.

### PR DESCRIPTION
**Pull request by pirj**
fixes #852

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [changelog](https://github.com/rubocop-hq/rubocop-rspec/blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
Config build failure is due to https://github.com/lsegal/yard/pull/1296

File: lib/rubocop/cop/rspec/instance_variable.rb [hunk 1]
```diff
@@ -67,6 +74,7 @@ def on_block(node)
 
           ivar_usage(node) do |ivar, name|
             return if inside_dynamic_class?(ivar)
+            return if inside_custom_matcher?(ivar)
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/instance_variable.rb]: I'd just rename the `inside_dunamic_class?` method and modify the block inside to check for both cases. It would be easier to extend (no more conditions added here) and will perform only one lookup up in the tree.

example name:
`return if valid_usage?(ivar)`

File: spec/rubocop/cop/rspec/instance_variable_spec.rb [hunk 2]
```diff
@@ -67,6 +67,41 @@ def serialize
     RUBY
   end
 
+  context 'when used in a custom matcher' do
+    it 'ignores instance variables inside `mather`' do
+      expect_no_offenses(<<~RUBY)
```
Comment (Darhazer) [inline spec/rubocop/cop/rspec/instance_variable_spec.rb]: for full coverage, maybe add an instance usage (@matcher) outside of the matcher definition?

Comment (pirj) [reply spec/rubocop/cop/rspec/instance_variable_spec.rb]: Sometimes I see you as a clairvoyant, Maxim, that spec immediately helped to find a bug. 👍

**Comment by pirj** [comment]
Green 👍 
Not sure if it makes sense to mention the second bug fixed in the changelist.

File: spec/rubocop/cop/rspec/instance_variable_spec.rb [hunk 3]
```diff
@@ -31,6 +31,18 @@
     RUBY
   end
 
+  it 'flags sefveral instance variables inside a describe' do
```
Comment (bquorning) [inline spec/rubocop/cop/rspec/instance_variable_spec.rb]:
```suggestion
  it 'flags several instance variables inside a describe' do
```

**Comment by pirj** [comment]
@bquorning Thanks for the fix.
Squashed, green.
