### PR TITLE
[Fix #712] check that the method is called on `receive`

### LINKED ISSUE #712: False positive for RSpec/ReceiveCounts auto-correction
Whilst running `rubocop --safe-auto-correct` on a large code base, I encountered the following error:

```
C: RSpec/ReceiveCounts: Use .twice instead of .exactly(2).times.
      expect { described_class.perform_now }.to have_published_event.exactly(2).times
                                                                    ^^^^^^^^^^^^^^^^^
```

The issue is that `have_published_event` is a custom class, which did not define a `#twice` method.

I have now gone ahead and defined this method. But the important point I wish to raise is that this autocorrection should be flagged as "unsafe" (and therefore not be run by `--safe-auto-correct`), since it cannot know its receiver.

### PR DESCRIPTION
**Pull request by Darhazer**
The cop didn't check that the receiver is actually a stub, leading to false positives if other objects implement similar API

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [changelog](https://github.com/rubocop-hq/rubocop-rspec/blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by Darhazer** [comment]
I switched to just skipping the auto-correct, but still flagging, as if you are going to mimic RSpec API, better mimic it completely :)

I'll add Safe/SafeAutocorrect config to cops, following the 0.60 release, in a separate PR.

File: spec/rubocop/cop/rspec/receive_counts_spec.rb [hunk 1]
```diff
@@ -78,11 +78,23 @@
     RUBY
   end
 
+  it 'flags exactly(1).times when not called on `receive`' do
```
Comment (bquorning) [inline spec/rubocop/cop/rspec/receive_counts_spec.rb]: 1 or 2? :-)

**Comment by bquorning** [comment]
It seems a bit weird to have a cop suggesting alternative code that won’t work… I guess the `Safe`/`SafeAutocorrect` PR will fix that?

**Comment by Darhazer** [comment]
> It seems a bit weird to have a cop suggesting alternative code that won’t work… I guess the Safe/SafeAutocorrect PR will fix that?

I'm a bit on a fence on this as well, but it will suggest a better API. The cop will not run under `--safe` in this case. Which I don't like much, maybe it's better to be it's own option `Safe`, so it reports offenses, ignoring the false positives....

In the implementation, is just deciding where to add the check for stub. We just have to make a decision about whether to suggest changing the API (which might not be in the control of the user anyway) or we will skip on those cases.

File: spec/rubocop/cop/rspec/receive_counts_spec.rb (hunk 1 above)
Comment (Darhazer) [reply spec/rubocop/cop/rspec/receive_counts_spec.rb]: Fixed

**Comment by Darhazer** [comment]
Rebased and changed the cop not to report the error

**Comment by Darhazer** [comment]
@bquorning what about this one and doing a bug-fix release after?
