### PR TITLE
Enforce dynamic attributes with explicit receiver

### LINKED ISSUE #687: Autocorrect skipped for FactoryBot/AttributeDefinedStatically in some cases
When an attribute is passed in the `do/end` block and used to define the value, autocorrection of the `FactoryBot/AttributeDefinedStatically` cop does not work.

Given this factory,

```ruby
factory :user do |f| 
  f.first_name 'John' # not being autocorrected
  last_name 'Doe'     # autocorrected properly
end 
```

it doesn't take into consideration the `first_name` attribute because of the `f.` before:
```ruby
# After running autocorrection

factory :user do |f| 
  f.first_name 'John'
  last_name { 'Doe' }
end 
```

Useful informations:
- Rubocop: `0.59.1 (using Parser 2.5.1.2, running on ruby 2.3.3 x86_64-darwin17)`
- Rubocop RSpec: `1.29.1`
- FactoryBot: `4.11.1`

### PR DESCRIPTION
**Pull request by composerinteralia**
Fixes #687

factory_bot allows you to define attributes on an explicit receiver by
passing in the definition proxy as the first argument to the block.

This is not quite ready to be merged, but I wanted to get some feedback before going any further. Does this approach make sense to you?

The class is too big, so I will have to move some things around to get the build to pass. Any advice on the best way to break this up?

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [X] Squashed related commits together.
* [X] Added tests.
* [x] Added an entry to the [changelog](https://github.com/rubocop-hq/rubocop-rspec/blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: spec/rubocop/cop/rspec/factory_bot/attribute_defined_statically_spec.rb [hunk 1]
```diff
@@ -98,6 +113,16 @@
     RUBY
   end
 
+  it 'does not add offense it method called on another object' do
```
Comment (composerinteralia) [inline spec/rubocop/cop/rspec/factory_bot/attribute_defined_statically_spec.rb]: oops. "it" -> "if"

File: spec/rubocop/cop/rspec/factory_bot/attribute_defined_statically_spec.rb [hunk 2]
```diff
@@ -66,6 +66,21 @@
     RUBY
   end
 
+  it 'registers an offense for attributes defined on explicit receiver' do
+    expect_offense(<<-RUBY)
+      FactoryBot.define do
+        factory :post do |post_definition|
+          post_definition.end Date.tomorrow
+          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Use a block to declare attribute values.
+          post_defintion.trait :published do |published_definition|
```
Comment (jonatas) [inline spec/rubocop/cop/rspec/factory_bot/attribute_defined_statically_spec.rb]: typo: `post_defintion` -> `post_defintion`

File: lib/rubocop/cop/rspec/factory_bot/attribute_defined_statically.rb [hunk 3]
```diff
@@ -88,6 +89,20 @@ def autocorrect(node)
 
           private
 
+          def offensive_receiver?(receiver, node)
```
Comment (jonatas) [inline lib/rubocop/cop/rspec/factory_bot/attribute_defined_statically.rb]: I guess we can manage to solve this problem by mixing custom methods with node pattern. Example:

```ruby
          def capture_arg(sym)
            @block_argument = sym
          end

          def from_capture?(node)
            node.node_parts == [@block_argument]
          end
```

and then we need to use the capture arg and the function to compare the nodes:

```ruby
          def_node_matcher :value_matcher, <<-PATTERN
            (send { self nil? (lvar #capture_arg) } !#reserved_method? $...)
          PATTERN

          def_node_search :factory_attributes, <<-PATTERN
            (block (send {nil? #from_capture?} #attribute_defining_method? ...) _ { (begin $...) $(send ...) } )
          PATTERN
```

**Comment by composerinteralia** [comment]
Sorry it took so long for me to come back to this.

@jonatas thanks for the review - I took your suggestions.

I ended up moving the constants out of this specific cop and onto `RuboCop::RSpec::FactoryBot`, but then on rebasing realized that the module was removed in https://github.com/rubocop-hq/rubocop-rspec/commit/a5df6e2588401982b80ce8036614231d78aa4745#diff-3b3465ed7d5d185d4bfa9acc4d26546f. I am open to other suggestions on how to organize things.

**Comment by bquorning** [comment]
The module was removed only because it was empty. You’re welcome to add the module back with some contents :-)

File: lib/rubocop/cop/rspec/factory_bot/attribute_defined_statically.rb [hunk 4]
```diff
@@ -27,47 +27,12 @@ module FactoryBot
...
-          ].freeze
-
-          RESERVED_METHODS =
-            DEFINITION_PROXY_METHODS +
-            UNPROXIED_METHODS +
-            ATTRIBUTE_DEFINING_METHODS
-
           def_node_matcher :value_matcher, <<-PATTERN
-            (send {self nil?} !#reserved_method? $...)
+            (send { self nil? (lvar #capture_arg) } !#reserved_method? $...)
```
Comment (Darhazer) [inline lib/rubocop/cop/rspec/factory_bot/attribute_defined_statically.rb]: Generally, you can use `%` in the pattern to pass variables, and avoid using the instance variable this way

Comment (composerinteralia) [reply lib/rubocop/cop/rspec/factory_bot/attribute_defined_statically.rb]: Interesting. I am unsure how to do use that. Is there documentation somewhere? Or an example?

I realized that when I took the suggestion to use instance variables I also introduced a regression that hadn't been tested, so I added a test case for it and went back to the version I had before for now.
