### PR TITLE
[Fix #728] Fix false negatives in Focus cop

### LINKED ISSUE #728: RSpec/Focus not working when I use RSpec.describe
RSpec/Focus not working against `RSpec.describe` 
Is it correct?

```ruby
# RSpec/Focus working
describe SomeClass, focus: true do
end

# RSpec/Focus not working
RSpec.describe SomeClass, focus: true do
end
```

`rubocop-0.62.0`
`rubocop-rspec-1.31.0`

### PR DESCRIPTION
**Pull request by Darhazer**
A while ago we made sure that our matchers include both explicit `RSpec` receiver and implicit (`nil?`) one. There were a couple of cops however that use just `node_pattern_union`, skipping the language module, and using only implicit receiver.

---

Before submitting the PR make sure the following are checked:

* [ ] Feature branch is up-to-date with `master` (if not - rebase it).
* [ ] Squashed related commits together.
* [ ] Added tests.
* [ ] Added an entry to the [changelog](https://github.com/rubocop-hq/rubocop-rspec/blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [ ] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

If you have created a new cop:

* [ ] Added the new cop to `config/default.yml`.
* [ ] The cop documents examples of good and bad code.
* [ ] The tests assert both that bad code is reported and that good code is not reported.

### CODE REVIEW

File: lib/rubocop/cop/rspec/focus.rb [hunk 1]
```diff
@@ -36,8 +36,8 @@ class Focus < Cop
         FOCUS_TRUE   = s(:pair, FOCUS_SYMBOL, s(:true))
 
         def_node_matcher :metadata, <<-PATTERN
-          {(send nil? #{FOCUSABLE_SELECTORS} ... (hash $...))
-           (send nil? #{FOCUSABLE_SELECTORS} $...)}
+          {(send {(const nil? :RSpec) nil?} #{FOCUSABLE_SELECTORS} ... (hash $...))
+           (send {(const nil? :RSpec) nil?} #{FOCUSABLE_SELECTORS} $...)}
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/focus.rb]: Should we extract `{(const nil? :RSpec) nil?}` to the `Language` module?

**Comment by Darhazer** [comment]
> I think one spec is failing after rubocop-hq/rubocop#6170 was merged into RuboCop 0.63.1.

Actually, a failing auto-correct for which we don't have a spec. Seems that now each `expect_offence` also run auto-correction which helps catch at least when auto-correct would crash. So now I have 2 more tasks: fix auto-correction and improve the `{(const nil? :RSpec) nil?}` usage :joy:

**Comment by bquorning** [comment]
> So now I have 2 more tasks

Or, you can delegate :-)

**Comment by Darhazer** [comment]
Build passes. Extraction of ` {(const nil? :RSpec) nil?}` will be a follow-up
