### PR TITLE
Fix multiple cops to detect `let` with proc argument

### LINKED ISSUE #771: RSpec/ScatteredLet unexpected behavior on let(:x, &proc)
I've come to a weird use of `let` today:

```ruby
shared_examples 'validate event_type' do |args|
  ...
  let(:expected_event_type_to_use, &args[:event_type_to_use])
  ...
end

...
it_behaves_like 'validate event_type', event_type_to_use: -> { event_type_sub.id }
...
```

Not going to discussion if this was a good use or not, it just works. RuboCop is flagging it wrongly though: it seems that it does not flag it as `let` and therefore all the `let`s below it are flagged by `RSpec/ScatteredLet`:
```text
159:7  warning  rubocop:C  RSpec/ScatteredLet: Group all let/let! blocks in the example group together.
 164:7  warning  rubocop:C  RSpec/ScatteredLet: Group all let/let! blocks in the example group together.
 165:7  warning  rubocop:C  RSpec/ScatteredLet: Group all let/let! blocks in the example group together.
 180:7  warning  rubocop:C  RSpec/ScatteredLet: Group all let/let! blocks in the example group together.
 185:7  warning  rubocop:C  RSpec/ScatteredLet: Group all let/let! blocks in the example group together.
 190:7  warning  rubocop:C  RSpec/ScatteredLet: Group all let/let! blocks in the example group together.
 195:7  warning  rubocop:C  RSpec/ScatteredLet: Group all let/let! blocks in the example group together.
```

Version info:
```
⋊> ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
⋊> rails -v
Rails 5.2.3
⋊> bundle exec rubocop -v
0.64.0
```

### PR DESCRIPTION
**Pull request by tejasbubane**
Closes #771

---

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [ ] Updated documentation.
* [x] Added an entry to the [changelog](https://github.com/rubocop-hq/rubocop-rspec/blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: lib/rubocop/rspec/language/node_pattern.rb [hunk 1]
```diff
@@ -17,7 +17,11 @@ module NodePattern
 
         def_node_matcher :hook?, Hooks::ALL.block_pattern
 
-        def_node_matcher :let?, Helpers::ALL.block_pattern
+        def_node_matcher :let?, <<-PATTERN
+          {#{Helpers::ALL.block_pattern}
+           (send #{RSPEC} #{Helpers::ALL.node_pattern_union}
+                 _ (block_pass ...))}
```
Comment (tejasbubane) [inline lib/rubocop/rspec/language/node_pattern.rb:23]: Instead of using `Helpers::ALL.send_pattern`, I thought it would be better to check for `block_pass` only.

Comment (pirj) [inline lib/rubocop/rspec/language/node_pattern.rb:23]: Will it work like that (no arg check at all for `block_pass`)?
```
{
  #{Helpers::ALL.block_pattern}
  (send #{RSPEC} #{Helpers::ALL.node_pattern_union} _ block_pass)
}
```

Comment (tejasbubane) [reply lib/rubocop/rspec/language/node_pattern.rb]: works! :)

**Comment by Darhazer** [comment]
WDYT of adding `block_or_block_pass_patern` to the Language? cc: @bquorning

**Comment by pirj** [comment]
> WDYT of adding block_or_block_pass_patern to the Language? 

Makes sense, this might simplify lib/rubocop/cop/rspec/factory_bot/attribute_defined_statically.rb

**Comment by bquorning** [comment]
> `block_or_block_pass_patern`

@Darhazer could you open a new issue for that? Or maybe a PR to showcase the change.

**Comment by Darhazer** [comment]
Sure :+1:

**Comment by tejasbubane** [comment]
@bquorning @Darhazer I added `block_or_block_pass_pattern` here.

**Comment by tejasbubane** [comment]
@pirj Added specs for those other cops as well.

**Comment by pirj** [comment]
Thank you!
