### PR TITLE
[Fix #624] Don't check let declarations with dynamic arguments

### LINKED ISSUE #624: RSpec/OverwritingSetup crashes on non-symbol setup names
I have some code that does something roughly along the lines of

```ruby
RSpec.describe Foo do
  let(:params) do
    {
      a: a,
      b: b
    }
  end

  let(:a) { 1 }
  let(:b) { 2 }

  %i[a b].each do |parameter|
    context "when #{parameter} is missing"  do
      let(name) { nil }

      it 'is not valid' do
        expect(Foo.new(params)).not_to be_valid
      end
    end
  end
end
```

I probably would't write the spec in that way today, but I'm sure I'm not the only person who's written setup using a dynamic name at some point in time.

Unfortunately, RSpec/OverwritingSetup now crashes in this case because it assumes a string/symbol will be present. We should update the node pattern or add a guard to make sure the argument to `let`, `subject`, etc. is actually a string or symbol we can compare.

Minimized reproduction:

```ruby
RSpec.describe 'test' do
  let(:foo) { 'foo' }
  name = :bar
  let(name) { 'bar' }
end
```

Trace:

> An error occurred while RSpec/OverwritingSetup cop was inspecting /Users/gollahon/dev/foo_spec.rb:1:0.
undefined method `value' for s(:lvar, :name):RuboCop::AST::Node
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:51:in `block in find_duplicates'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:185:in `block in each_child_node'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:183:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/node.rb:183:in `each_child_node'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:47:in `find_duplicates'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:34:in `on_block'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:105:in `with_cop_error_handling'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:55:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/commissioner.rb:45:in `investigate'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:114:in `investigate'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:102:in `offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:265:in `inspect_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:212:in `block in do_inspection_loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:244:in `block in iterate_until_no_changes'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:237:in `loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:237:in `iterate_until_no_changes'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:208:in `do_inspection_loop'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:129:in `file_offense_cache'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:100:in `process_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `each'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `reduce'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/runner.rb:39:in `run'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:160:in `execute_runner'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:88:in `execute_runners'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/lib/rubocop/cli.rb:41:in `run'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/exe/rubocop:13:in `block in <top (required)>'
/Users/gollahon/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/Users/gollahon/.rvm/gems/ruby-2.5.1/gems/rubocop-0.57.0/exe/rubocop:12:in `<top (required)>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/rubocop:23:in `load'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/rubocop:23:in `<main>'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/Users/gollahon/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'

### PR DESCRIPTION
**Pull request by Darhazer**
Only basic_literals define `#value` method.

Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [changelog](https://github.com/rubocop-hq/rubocop-rspec/blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: spec/rubocop/cop/rspec/overwriting_setup_spec.rb [hunk 1]
```diff
@@ -66,6 +66,16 @@
     RUBY
   end
 
+  it 'handles dynamic names for `let`' do
+    expect_no_offenses(<<-RUBY)
+      RSpec.describe User do
+        subject(:name) { a }
```
Comment (bquorning) [inline spec/rubocop/cop/rspec/overwriting_setup_spec.rb]: Did you mean `:a` here?

Comment (Darhazer) [reply spec/rubocop/cop/rspec/overwriting_setup_spec.rb]: Doesn't really matter

**Comment by bquorning** [comment]
It looks like we have a problem with the jruby build image. I have temporarily marked `ci/circleci: jruby` as a *not* required status check so you can continue working.

File: lib/rubocop/cop/rspec/overwriting_setup.rb [hunk 2]
```diff
@@ -44,18 +42,25 @@ def on_block(node)
...
 
             yield child, name unless setup_expressions.add?(name)
           end
         end
+
+        def common_setup?(node)
+          return false unless setup?(node)
+          # Search only for setup with basic_literal arguments (e.g. :sym, :str)
+          # or no arguments at all.
+          node.send_node.arguments.all?(&:basic_literal?)
```
Comment (dgollahon) [inline lib/rubocop/cop/rspec/overwriting_setup.rb]: Because of what you mentioned here https://github.com/rubocop-hq/rubocop-rspec/issues/624#issuecomment-395403485 will this also skip strings?

File: lib/rubocop/cop/rspec/overwriting_setup.rb [hunk 3]
```diff
@@ -44,18 +42,25 @@ def on_block(node)
...
         def find_duplicates(node)
           setup_expressions = Set.new
-          node.each_child_node do |child|
-            next unless setup?(child)
+          node.each_child_node(:block) do |child|
+            next unless common_setup?(child)
 
             name = if child.send_node.arguments?
-                     child.send_node.first_argument.value
+                     child.send_node.first_argument.to_a.first.to_sym
```
Comment (dgollahon) [inline lib/rubocop/cop/rspec/overwriting_setup.rb]: Related to my question below, if you check that it's a `basic_literal?` first, can you just use `.value` as before?

File: lib/rubocop/cop/rspec/overwriting_setup.rb (hunk 2 above)
Comment (Darhazer) [reply lib/rubocop/cop/rspec/overwriting_setup.rb]: It will check str but not dstr or xstr

File: lib/rubocop/cop/rspec/overwriting_setup.rb (hunk 3 above)
Comment (Darhazer) [reply lib/rubocop/cop/rspec/overwriting_setup.rb]: Nope, str doesn’t provide value

**Comment by Darhazer** [comment]
@bquorning approve?

File: lib/rubocop/cop/rspec/overwriting_setup.rb (hunk 3 above)
Comment (bquorning) [reply lib/rubocop/cop/rspec/overwriting_setup.rb]: `child.send_node.first_argument.to_a.first.to_sym` – I don’t understand this line. Would it be possible to use a beautifully named local variable or two, to make it more readable?

**Comment by Darhazer** [comment]
@bquorning I've changed the code to use a node-matcher in a new commit. Does it read better now?

File: lib/rubocop/cop/rspec/overwriting_setup.rb [hunk 4]
```diff
@@ -44,18 +43,25 @@ def on_block(node)
...
         def find_duplicates(node)
           setup_expressions = Set.new
-          node.each_child_node do |child|
-            next unless setup?(child)
+          node.each_child_node(:block) do |child|
+            next unless common_setup?(child)
 
             name = if child.send_node.arguments?
-                     child.send_node.first_argument.value
+                     first_argument_name(child.send_node).to_sym
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/overwriting_setup.rb]: ❤️

**Comment by bquorning** [comment]
I think this is much better. Thank you.
