### PR TITLE
Fix #702: don't flag n.times block with an argument

### LINKED ISSUE #702: CreateList with index
```yaml
FactoryBot/CreateList:
  EnforcedStyle: create_list
```
```
test 'create list test' do
  3.times { |n| create :user, created_at: n.months.ago }
end
```
```bash
spec/test_spec.rb:4:3: C: FactoryBot/CreateList: Prefer create_list.
  3.times { |n| create :user, created_at: n.months.ago }
  ^^^^^^^
```

Based on the [docs](https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/CreateList) this should not be failing:
```
# bad
3.times { create :user }

# good
create_list :user, 3

# good
3.times { |n| create :user, created_at: n.months.ago }
```

Versions: 
  - rubocop (0.59.2)
  - rubocop-rspec (1.29.1)

### PR DESCRIPTION
**Pull request by Darhazer**
Before submitting the PR make sure the following are checked:

* [x] Feature branch is up-to-date with `master` (if not - rebase it).
* [x] Squashed related commits together.
* [x] Added tests.
* [x] Added an entry to the [changelog](https://github.com/rubocop-hq/rubocop-rspec/blob/master/CHANGELOG.md) if the new code introduces user-observable changes.
* [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

File: lib/rubocop/cop/rspec/factory_bot/create_list.rb [hunk 1]
```diff
@@ -30,9 +30,10 @@ class CreateList < Cop
           MSG_CREATE_LIST = 'Prefer create_list.'.freeze
           MSG_N_TIMES = 'Prefer %<number>s.times.'.freeze
 
-          def_node_matcher :n_times_block?, <<-PATTERN
+          def_node_matcher :n_times_block_without_arg?, <<-PATTERN
             (block
               (send (int _) :times)
+              (args)
```
Comment (bquorning) [inline lib/rubocop/cop/rspec/factory_bot/create_list.rb]: What does `(args)` mean here? Without arg?

Comment (Darhazer) [reply lib/rubocop/cop/rspec/factory_bot/create_list.rb]: empty arguments list, e.g. no `| |` in the block

Comment (bquorning) [reply lib/rubocop/cop/rspec/factory_bot/create_list.rb]: Ah, of course. It would be e.g. `(args _)` if there were any arguments.
